### PR TITLE
[CHERI-MIPS] Clear C13 when passing no arguments to variadic functions

### PR DESCRIPTION
**Pull request by jrtc27**

### CODE REVIEW

**Review by arichardson — COMMENTED** [review]
> the logic in MipsISelLowering for whether to null out
C13 is conditional on the optimisation level under the guise of
debugging, which for some strange reason (and one that I think should
go) is still enabled at -O1 but not -O2, so we want to be sure we're
checking the non-debugging version too.

I agree this should either be dropped entirely or be O0 only. The compiler is much more mature than it was when that code was added.

**Comment by jrtc27** [comment]
> > the logic in MipsISelLowering for whether to null out
> > C13 is conditional on the optimisation level under the guise of
> > debugging, which for some strange reason (and one that I think should
> > go) is still enabled at -O1 but not -O2, so we want to be sure we're
> > checking the non-debugging version too.
> 
> I agree this should either be dropped entirely or be O0 only. The compiler is much more mature than it was when that code was added.

I'm all for dropping it entirely, I don't like even -O0 code behaving differently beyond not running optimisation passes. Will update the PR to do that before adding the bug fix.

**Review by arichardson — APPROVED** [review]
Looks great.

**Comment by jrtc27** [comment]
> Looks great.

Uh, other than the typo in the second commit's subject... will fix :)

**Review by arichardson — APPROVED** [review]

**Pull request merged**
