### PR TITLE
[CHERI-RISC-V] Fix ptrtoint pattern for NULL inputs

### PR DESCRIPTION
**Pull request by arichardson**
Using a constant physical register on the input side of the pattern does
not work correctly (in my testing it appears to match any capability
register, but that's already handled by the earlier patterns).
Use the "constant NULL pattern" (inttoptr 0) instead.

This allows emitting `li a0, 0` in hybrid instead of ctoptr and also
allows us to fold a subsequent add since we now have a COPY node.

### CODE REVIEW

**Comment by jrtc27** [comment]
> (in my testing it appears to match any capability register, but that's already handled by the earlier patterns)

That's odd, are you sure it's not just that another pattern, e.g. the earlier one, was matching it?

**Review by jrtc27 — APPROVED** [review]
Changes are fine, though I do wonder if this is better served in InstCombine and/or DAGCombine rather than being target-specific

**Comment by arichardson** [comment]
> Changes are fine, though I do wonder if this is better served in InstCombine and/or DAGCombine rather than being target-specific

I agree that more complete folding should be done somewhere else, we just get this minimal folding for free by fixing the NULL pattern (which wasn't being used before).

**Comment by arichardson** [comment]
> > (in my testing it appears to match any capability register, but that's already handled by the earlier patterns)
> 
> That's odd, are you sure it's not just that another pattern, e.g. the earlier one, was matching it?

The weirdness happened when I commented out the previous pattern, the debugger showed that this pattern was being matched and we were generating a nonsense copytoreg node instead...

**Comment by jrtc27** [comment]
> > > (in my testing it appears to match any capability register, but that's already handled by the earlier patterns)
> > 
> > 
> > That's odd, are you sure it's not just that another pattern, e.g. the earlier one, was matching it?
> 
> The weirdness happened when I commented out the previous pattern, the debugger showed that this pattern was being matched and we were generating a nonsense copytoreg node instead...

🤷‍♀️ garbage in garbage out I guess... blame past me

**Pull request merged**
