### PR TITLE
morello: add a clear_cache implementation

### PR DESCRIPTION
**Pull request by brooksdavis**
Obtained from: Morello LLVM 61c84c16ae7e1468e7c12fd33098362081d68335

### CODE REVIEW

**Comment by jrtc27** [comment]
I personally think something like:
```diff
diff --git a/contrib/llvm-project/compiler-rt/lib/builtins/clear_cache.c b/contrib/llvm-project/compiler-rt/lib/builtins/clear_cache.c
index 7364eb0443dd..cc21744158b0 100644
--- a/contrib/llvm-project/compiler-rt/lib/builtins/clear_cache.c
+++ b/contrib/llvm-project/compiler-rt/lib/builtins/clear_cache.c
@@ -92,25 +92,25 @@ void __clear_cache(void *start, void *end) {
   cacheflush(start, (uintptr_t)end - (uintptr_t)start, BCACHE);
 #elif defined(__aarch64__) && !defined(__APPLE__)
 #if defined(__CHERI_PURE_CAPABILITY__)
-  uintptr_t xstart = (uintptr_t)start;
-  uintptr_t xend = (uintptr_t)end;
+  typedef uintptr_t addr_type;
+#define ADDR_CONSTR "C"
 #else
-  uint64_t xstart = (uint64_t)(uintptr_t)start;
-  uint64_t xend = (uint64_t)(uintptr_t)end;
+  typedef uint64_t addr_type;
+#define ADDR_CONSTR "r"
 #endif
 
+  addr_type xstart = (addr_type)(uintptr_t)start;
+  addr_type xend = (addr_type)(uintptr_t)end;
+
   // Get Cache Type Info.
   static uint64_t ctr_el0 = 0;
   if (ctr_el0 == 0)
     __asm __volatile("mrs %0, ctr_el0" : "=r"(ctr_el0));
 
   // The DC and IC instructions must use 64-bit registers so we don't use
-  // uintptr_t in case this runs in an IPL32 environment.
-#if defined(__CHERI_PURE_CAPABILITY__)
-  uintptr_t addr;
-#else
-  uint64_t addr;
-#endif
+  // uintptr_t in case this runs in an IPL32 environment, unless compiling for
+  // C64 where we have to use a capability.
+  addr_type addr;
 
   // If CTR_EL0.IDC is set, data cache cleaning to the point of unification
   // is not required for instruction to data coherence.
@@ -118,11 +118,7 @@ void __clear_cache(void *start, void *end) {
     const size_t dcache_line_size = 4 << ((ctr_el0 >> 16) & 15);
     for (addr = xstart & ~(dcache_line_size - 1); addr < xend;
          addr += dcache_line_size)
-#if defined(__CHERI_PURE_CAPABILITY__)
-      __asm __volatile("dc cvau, %0" ::"C"(addr));
-#else
-      __asm __volatile("dc cvau, %0" ::"r"(addr));
-#endif
+      __asm __volatile("dc cvau, %0" :: ADDR_CONSTR(addr));
   }
   __asm __volatile("dsb ish");
 
@@ -132,13 +128,10 @@ void __clear_cache(void *start, void *end) {
     const size_t icache_line_size = 4 << ((ctr_el0 >> 0) & 15);
     for (addr = xstart & ~(icache_line_size - 1); addr < xend;
          addr += icache_line_size)
-#if defined(__CHERI_PURE_CAPABILITY__)
-      __asm __volatile("ic ivau, %0" ::"C"(addr));
-#else
-      __asm __volatile("ic ivau, %0" ::"r"(addr));
-#endif
+      __asm __volatile("ic ivau, %0" :: ADDR_CONSTR(addr));
   }
   __asm __volatile("isb sy");
+#undef ADDR_CONSTR
 #elif defined(__powerpc64__)
   const size_t line_size = 32;
   const size_t len = (uintptr_t)end - (uintptr_t)start;
```
makes it cleaner (at which point there is basically none of Arm's code left and the diff to upstream is more minimal). Names can be debated, but the principle is the same.

**Comment by brooksdavis** [comment]
Seems sensible. Should we upstream that directly or just let it conflict in a future merge?

**Comment by jrtc27** [comment]
You mean downstream? :P

**Comment by jrtc27** [comment]
Fixed by https://github.com/CTSRD-CHERI/llvm-project/commit/0d426e672f7b001e3f17b066e3bcc55e1add212d.

**Pull request closed without merging**
