### PR TITLE
cheri-rvc compiler rt

### PR DESCRIPTION
**Pull request by heshamelmatary**

### CODE REVIEW

**Comment by jrtc27** [comment]
This is independent of RVC, no?

**Comment by heshamelmatary** [comment]
> This is independent of RVC, no?

I would think so, but I only get an error when building with -mxcheri-rvc for some reason

**Comment by heshamelmatary** [comment]
Is `ret` pseudo-code CHERI-aware?

**Comment by jrtc27** [comment]
Hm, seems I never banned that pseudo-instruction for purecap code... I could have sworn I did, but apparently not, I did the CodeGen pseudos and call+tail assembly but not the ret alias despite it being a silly thing to write in purecap code.

You should still see the error with this branch but no -mxcheri-rvc though, as this branch fixes that issue (since not only is it silly to write, it also no longer maps to JALR as that doesn't exist in capability mode).

**Comment by jrtc27** [comment]
#571

**Pull request closed without merging**
